"""split parcel order sender receiver

Revision ID: 0c5230776947
Revises: 5723142f41f5
Create Date: 2026-08-07 12:20:09.961030

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '0c5230776947'
down_revision: Union[str, None] = '5723142f41f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_orders', sa.Column('sender_id', sa.String(length=36), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_parcel_orders_receiver_id'), 'parcel_orders', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_parcel_orders_sender_id'), 'parcel_orders', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'parcel_orders', 'parcel_senders', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parcel_orders', 'parcel_receivers', ['receiver_id'], ['id'], ondelete='SET NULL')
    op.drop_column('parcel_orders', 'receiver_mobile')
    op.drop_column('parcel_orders', 'sender_address_line_2')
    op.drop_column('parcel_orders', 'sender_lat')
    op.drop_column('parcel_orders', 'sender_alternate_mobile')
    op.drop_column('parcel_orders', 'sender_address_line_1')
    op.drop_column('parcel_orders', 'receiver_pincode')
    op.drop_column('parcel_orders', 'receiver_state')
    op.drop_column('parcel_orders', 'sender_name')
    op.drop_column('parcel_orders', 'sender_mobile')
    op.drop_column('parcel_orders', 'receiver_email')
    op.drop_column('parcel_orders', 'receiver_alternate_mobile')
    op.drop_column('parcel_orders', 'receiver_name')
    op.drop_column('parcel_orders', 'sender_email')
    op.drop_column('parcel_orders', 'receiver_city')
    op.drop_column('parcel_orders', 'receiver_address_line_1')
    op.drop_column('parcel_orders', 'sender_state')
    op.drop_column('parcel_orders', 'sender_city')
    op.drop_column('parcel_orders', 'receiver_address_line_2')
    op.drop_column('parcel_orders', 'sender_lng')
    op.drop_column('parcel_orders', 'sender_pincode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_orders', sa.Column('sender_pincode', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_lng', mysql.FLOAT(), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_address_line_2', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_state', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_address_line_1', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_name', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_alternate_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_name', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_state', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_pincode', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_address_line_1', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_alternate_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_lat', mysql.FLOAT(), nullable=True))
    op.add_column('parcel_orders', sa.Column('sender_address_line_2', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('parcel_orders', sa.Column('receiver_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'parcel_orders', type_='foreignkey')
    op.drop_constraint(None, 'parcel_orders', type_='foreignkey')
    op.drop_index(op.f('ix_parcel_orders_sender_id'), table_name='parcel_orders')
    op.drop_index(op.f('ix_parcel_orders_receiver_id'), table_name='parcel_orders')
    op.drop_column('parcel_orders', 'receiver_id')
    op.drop_column('parcel_orders', 'sender_id')
    # ### end Alembic commands ###
