"""Refactor parcel_tripsheet

Revision ID: 101bba7fbca3
Revises: 6f2df0c6f297
Create Date: 2026-08-06 16:20:41.370171

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '101bba7fbca3'
down_revision: Union[str, None] = '6f2df0c6f297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_tripsheets', sa.Column('driver_name', sa.String(length=150), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('vehicle_number', sa.String(length=50), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('vehicle_type', sa.String(length=100), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('vehicle_model', sa.String(length=100), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('fuel_type', sa.String(length=50), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('created_by', sa.String(length=36), nullable=False))
    op.add_column('parcel_tripsheets', sa.Column('franchise_id', sa.String(length=36), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_parcel_tripsheets_trip_number'), table_name='parcel_tripsheets')
    op.create_index(op.f('ix_parcel_tripsheets_created_by'), 'parcel_tripsheets', ['created_by'], unique=False)
    op.create_index(op.f('ix_parcel_tripsheets_franchise_id'), 'parcel_tripsheets', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_parcel_tripsheets_warehouse_id'), 'parcel_tripsheets', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'parcel_tripsheets', 'franchises', ['franchise_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parcel_tripsheets', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parcel_tripsheets', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.drop_column('parcel_tripsheets', 'trip_number')
    op.drop_column('parcel_tripsheets', 'drivers_list')
    op.drop_column('parcel_tripsheets', 'vehicle_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_tripsheets', sa.Column('vehicle_details', mysql.JSON(), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('drivers_list', mysql.JSON(), nullable=True))
    op.add_column('parcel_tripsheets', sa.Column('trip_number', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'parcel_tripsheets', type_='foreignkey')
    op.drop_constraint(None, 'parcel_tripsheets', type_='foreignkey')
    op.drop_constraint(None, 'parcel_tripsheets', type_='foreignkey')
    op.drop_index(op.f('ix_parcel_tripsheets_warehouse_id'), table_name='parcel_tripsheets')
    op.drop_index(op.f('ix_parcel_tripsheets_franchise_id'), table_name='parcel_tripsheets')
    op.drop_index(op.f('ix_parcel_tripsheets_created_by'), table_name='parcel_tripsheets')
    op.create_index(op.f('ix_parcel_tripsheets_trip_number'), 'parcel_tripsheets', ['trip_number'], unique=True)
    op.drop_column('parcel_tripsheets', 'warehouse_id')
    op.drop_column('parcel_tripsheets', 'franchise_id')
    op.drop_column('parcel_tripsheets', 'created_by')
    op.drop_column('parcel_tripsheets', 'fuel_type')
    op.drop_column('parcel_tripsheets', 'vehicle_model')
    op.drop_column('parcel_tripsheets', 'vehicle_type')
    op.drop_column('parcel_tripsheets', 'vehicle_number')
    op.drop_column('parcel_tripsheets', 'address')
    op.drop_column('parcel_tripsheets', 'country')
    op.drop_column('parcel_tripsheets', 'state')
    op.drop_column('parcel_tripsheets', 'city')
    op.drop_column('parcel_tripsheets', 'gender')
    op.drop_column('parcel_tripsheets', 'email')
    op.drop_column('parcel_tripsheets', 'mobile')
    op.drop_column('parcel_tripsheets', 'driver_name')
    # ### end Alembic commands ###
