"""Add auth_user_id to pickup_address and consignee and update order status enum

Revision ID: 31e6b3d20eff
Revises: 316f13581470
Create Date: 2026-07-29 22:05:08.533876

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '31e6b3d20eff'
down_revision: Union[str, None] = '316f13581470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignees', sa.Column('auth_user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_consignees_auth_user_id'), 'consignees', ['auth_user_id'], unique=False)
    op.create_foreign_key(None, 'consignees', 'auth_users', ['auth_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('pickup_addresses', sa.Column('auth_user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_pickup_addresses_auth_user_id'), 'pickup_addresses', ['auth_user_id'], unique=False)
    op.create_foreign_key(None, 'pickup_addresses', 'auth_users', ['auth_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_trip_sheets_driver_status'), table_name='trip_sheets')
    op.create_index(op.f('ix_trip_sheets_driver_status'), 'trip_sheets', ['driver_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_sheets_driver_status'), table_name='trip_sheets')
    op.create_index(op.f('ix_trip_sheets_driver_status'), 'trip_sheets', ['driver_id', 'driver_status'], unique=False)
    op.drop_constraint(None, 'pickup_addresses', type_='foreignkey')
    op.drop_index(op.f('ix_pickup_addresses_auth_user_id'), table_name='pickup_addresses')
    op.drop_column('pickup_addresses', 'auth_user_id')
    op.drop_constraint(None, 'consignees', type_='foreignkey')
    op.drop_index(op.f('ix_consignees_auth_user_id'), table_name='consignees')
    op.drop_column('consignees', 'auth_user_id')
    # ### end Alembic commands ###
