"""Add warehouse_id to operations and order models

Revision ID: 3974e88e0e74
Revises: 3c65cc2cc5ec
Create Date: 2026-07-09 21:01:48.277850

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '3974e88e0e74'
down_revision: Union[str, None] = '3c65cc2cc5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulk_orders', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bulk_orders_warehouse_id'), 'bulk_orders', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'bulk_orders', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.add_column('cash_vouchers', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_cash_vouchers_warehouse_id'), 'cash_vouchers', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'cash_vouchers', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.add_column('expenses', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_expenses_warehouse_id'), 'expenses', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.add_column('invoices', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_invoices_warehouse_id'), 'invoices', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_orders_warehouse_id'), 'orders', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.add_column('remittances', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.alter_column('remittances', 'franchise_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_remittances_warehouse_id'), 'remittances', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'remittances', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.add_column('staff_attendance', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_staff_attendance_warehouse_id'), 'staff_attendance', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'staff_attendance', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_addresses', sa.Column('warehouse_code', mysql.VARCHAR(length=50), nullable=True))
    op.create_index(op.f('warehouse_code'), 'warehouse_addresses', ['warehouse_code'], unique=True)
    op.create_index(op.f('ix_warehouse_addresses_warehouse_code'), 'warehouse_addresses', ['warehouse_code'], unique=True)
    op.drop_constraint(None, 'staff_attendance', type_='foreignkey')
    op.drop_index(op.f('ix_staff_attendance_warehouse_id'), table_name='staff_attendance')
    op.drop_column('staff_attendance', 'warehouse_id')
    op.drop_constraint(None, 'remittances', type_='foreignkey')
    op.drop_index(op.f('ix_remittances_warehouse_id'), table_name='remittances')
    op.alter_column('remittances', 'franchise_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_column('remittances', 'warehouse_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_warehouse_id'), table_name='orders')
    op.alter_column('orders', 'is_gst_exempt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'is_manual_freight',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'total_freight',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'freight_gst',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'freight_charge',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'service_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Surface'"))
    op.drop_column('orders', 'warehouse_id')
    op.add_column('order_items', sa.Column('order_package_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('order_items_ibfk_2'), 'order_items', 'order_packages', ['order_package_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_order_items_order_package_id'), 'order_items', ['order_package_id'], unique=False)
    op.alter_column('notifications', 'order_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_warehouse_id'), table_name='invoices')
    op.alter_column('invoices', 'total_product_value',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.drop_column('invoices', 'warehouse_id')
    op.alter_column('invoice_orders', 'total_freight',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoice_orders', 'freight_gst',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoice_orders', 'freight_charge',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_warehouse_id'), table_name='expenses')
    op.drop_column('expenses', 'warehouse_id')
    op.drop_constraint(None, 'cash_vouchers', type_='foreignkey')
    op.drop_index(op.f('ix_cash_vouchers_warehouse_id'), table_name='cash_vouchers')
    op.drop_column('cash_vouchers', 'warehouse_id')
    op.drop_constraint(None, 'bulk_orders', type_='foreignkey')
    op.drop_index(op.f('ix_bulk_orders_warehouse_id'), table_name='bulk_orders')
    op.drop_column('bulk_orders', 'warehouse_id')
    op.create_table('wallets',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('franchise_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=14, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name=op.f('wallets_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_wallets_franchise_id'), 'wallets', ['franchise_id'], unique=True)
    op.create_table('wallet_transactions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('wallet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('opening_balance', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('wallet_transactions_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('wallet_transactions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_order_id'), 'wallet_transactions', ['order_id'], unique=False)
    # ### end Alembic commands ###
