"""add warehouse_id to users

Revision ID: 3aa6b509345d
Revises: 3974e88e0e74
Create Date: 2026-07-10 13:51:03.048049

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '3aa6b509345d'
down_revision: Union[str, None] = '3974e88e0e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_warehouse_id'), 'users', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'users', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_warehouse_id'), table_name='users')
    op.drop_column('users', 'warehouse_id')
    # ### end Alembic commands ###

