"""Add payment_status to Order

Revision ID: 3e7e7564d133
Revises: cd913e94121b
Create Date: 2026-07-31 21:39:48.765892

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3e7e7564d133'
down_revision: Union[str, None] = 'cd913e94121b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
