"""Add extra_charge to parcel_orders

Revision ID: 5723142f41f5
Revises: f605020f3ef5
Create Date: 2026-08-06 18:06:00.936042

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5723142f41f5'
down_revision: Union[str, None] = 'f605020f3ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_orders', sa.Column('extra_charge', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcel_orders', 'extra_charge')
    # ### end Alembic commands ###
