"""rename trip sheet route fields

Revision ID: 5ec447f29e9b
Revises: 
Create Date: 2026-07-21 11:38:53.082544

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '5ec447f29e9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS wallet_transactions')
    op.execute('DROP TABLE IF EXISTS wallets')
    op.alter_column('invoice_orders', 'freight_charge',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoice_orders', 'freight_gst',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoice_orders', 'total_freight',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoices', 'total_product_value',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('notifications', 'order_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(op.f('order_items_ibfk_2'), 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_order_package_id'), table_name='order_items')
    op.drop_column('order_items', 'order_package_id')
    op.alter_column('orders', 'service_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Surface'"))
    op.alter_column('orders', 'freight_charge',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'freight_gst',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'total_freight',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'is_manual_freight',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'is_gst_exempt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.add_column('trip_sheets', sa.Column('route_city', sa.JSON(), nullable=True))
    op.add_column('trip_sheets', sa.Column('destination_city', sa.String(length=255), nullable=True))
    op.drop_column('trip_sheets', 'route')
    op.drop_column('trip_sheets', 'destination')
    op.drop_index(op.f('warehouse_code'), table_name='warehouse_addresses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('warehouse_code'), 'warehouse_addresses', ['warehouse_code'], unique=True)
    op.add_column('trip_sheets', sa.Column('destination', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('trip_sheets', sa.Column('route', mysql.JSON(), nullable=True))
    op.drop_column('trip_sheets', 'destination_city')
    op.drop_column('trip_sheets', 'route_city')
    op.alter_column('orders', 'is_gst_exempt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'is_manual_freight',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'total_freight',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'freight_gst',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'freight_charge',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('orders', 'service_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Surface'"))
    op.add_column('order_items', sa.Column('order_package_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('order_items_ibfk_2'), 'order_items', 'order_packages', ['order_package_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_order_items_order_package_id'), 'order_items', ['order_package_id'], unique=False)
    op.alter_column('notifications', 'order_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('invoices', 'total_product_value',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoice_orders', 'total_freight',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoice_orders', 'freight_gst',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('invoice_orders', 'freight_charge',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.create_table('wallet_transactions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('wallet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('opening_balance', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('wallet_transactions_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('wallet_transactions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_order_id'), 'wallet_transactions', ['order_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('franchise_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=14, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name=op.f('wallets_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_wallets_franchise_id'), 'wallets', ['franchise_id'], unique=True)
    # ### end Alembic commands ###
