"""add month_end_closings table

Revision ID: 649f9609db1b
Revises: 826da0476dd9
Create Date: 2026-07-09 13:16:51.577814

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '649f9609db1b'
down_revision: Union[str, None] = '826da0476dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month_end_closings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_owner_name', sa.String(length=100), nullable=False),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('admin_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_month_end_closings_franchise_id'), 'month_end_closings', ['franchise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_month_end_closings_franchise_id'), table_name='month_end_closings')
    op.drop_table('month_end_closings')
    # ### end Alembic commands ###
