"""Add parcel_tripsheet table

Revision ID: 6f2df0c6f297
Revises: 80002787026d
Create Date: 2026-08-06 16:11:53.835629

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6f2df0c6f297'
down_revision: Union[str, None] = '80002787026d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_tripsheets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_number', sa.String(length=50), nullable=False),
    sa.Column('barcodes', sa.JSON(), nullable=False),
    sa.Column('drivers_list', sa.JSON(), nullable=True),
    sa.Column('vehicle_details', sa.JSON(), nullable=True),
    sa.Column('city_routes', sa.JSON(), nullable=True),
    sa.Column('city_destination', sa.String(length=200), nullable=True),
    sa.Column('starting_kilometer', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ending_kilometer', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Dispatched'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_tripsheets_trip_number'), 'parcel_tripsheets', ['trip_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_tripsheets_trip_number'), table_name='parcel_tripsheets')
    op.drop_table('parcel_tripsheets')
    # ### end Alembic commands ###
