"""Add warehouse_id to Driver and Vehicle

Revision ID: 777d33343dcb
Revises: 5ec447f29e9b
Create Date: 2026-07-23 11:37:25.762512

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '777d33343dcb'
down_revision: Union[str, None] = '5ec447f29e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_drivers_warehouse_id'), 'drivers', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'drivers', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.add_column('vehicles', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_vehicles_warehouse_id'), 'vehicles', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_warehouse_id'), table_name='vehicles')
    op.drop_column('vehicles', 'warehouse_id')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_index(op.f('ix_drivers_warehouse_id'), table_name='drivers')
    op.drop_column('drivers', 'warehouse_id')
    # ### end Alembic commands ###
