"""add parcel_orders table

Revision ID: 80002787026d
Revises: b2c53a77c0b1
Create Date: 2026-08-06 08:12:59.416479

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '80002787026d'
down_revision: Union[str, None] = 'b2c53a77c0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('sender_name', sa.String(length=150), nullable=True),
    sa.Column('sender_mobile', sa.String(length=20), nullable=True),
    sa.Column('sender_alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_address_line_1', sa.String(length=500), nullable=True),
    sa.Column('sender_address_line_2', sa.String(length=500), nullable=True),
    sa.Column('sender_pincode', sa.String(length=10), nullable=True),
    sa.Column('sender_city', sa.String(length=100), nullable=True),
    sa.Column('sender_state', sa.String(length=100), nullable=True),
    sa.Column('sender_lat', sa.Float(), nullable=True),
    sa.Column('sender_lng', sa.Float(), nullable=True),
    sa.Column('receiver_name', sa.String(length=150), nullable=True),
    sa.Column('receiver_mobile', sa.String(length=20), nullable=True),
    sa.Column('receiver_alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('receiver_email', sa.String(length=255), nullable=True),
    sa.Column('receiver_address_line_1', sa.String(length=500), nullable=True),
    sa.Column('receiver_address_line_2', sa.String(length=500), nullable=True),
    sa.Column('receiver_pincode', sa.String(length=10), nullable=True),
    sa.Column('receiver_city', sa.String(length=100), nullable=True),
    sa.Column('receiver_state', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('cod_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prepaid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('to_pay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rov', sa.String(length=20), nullable=True),
    sa.Column('order_value', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('service_type', sa.String(length=20), server_default=sa.text("'Surface'"), nullable=True),
    sa.Column('freight_charge', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('freight_gst', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total_freight', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('length_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('breadth_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_boxes', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('eway_bill_number', sa.String(length=30), nullable=True),
    sa.Column('invoicenumber', sa.Integer(), nullable=True),
    sa.Column('insurance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('regional_area', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Processing'"), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse_addresses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_orders_created_by'), 'parcel_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_parcel_orders_franchise_id'), 'parcel_orders', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_parcel_orders_order_number'), 'parcel_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_parcel_orders_warehouse_id'), 'parcel_orders', ['warehouse_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_parcel_orders_warehouse_id'), table_name='parcel_orders')
    op.drop_index(op.f('ix_parcel_orders_order_number'), table_name='parcel_orders')
    op.drop_index(op.f('ix_parcel_orders_franchise_id'), table_name='parcel_orders')
    op.drop_index(op.f('ix_parcel_orders_created_by'), table_name='parcel_orders')
    op.drop_table('parcel_orders')
    # ### end Alembic commands ###
