"""Add is_local, route and destination to trip_sheets

Revision ID: 8ea36cceb61b
Revises: c6bb09194e02
Create Date: 2026-07-20 12:45:32.947231

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '8ea36cceb61b'
down_revision: Union[str, None] = 'c6bb09194e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_sheets', sa.Column('is_local', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('trip_sheets', sa.Column('route', sa.String(length=255), nullable=True))
    op.add_column('trip_sheets', sa.Column('destination', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_sheets', 'destination')
    op.drop_column('trip_sheets', 'route')
    op.drop_column('trip_sheets', 'is_local')
    # ### end Alembic commands ###
