"""Add ParcelTripSheetOrder model

Revision ID: ac4a2d6f413f
Revises: 101bba7fbca3
Create Date: 2026-08-06 16:49:08.871757

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'ac4a2d6f413f'
down_revision: Union[str, None] = '101bba7fbca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcel_tripsheets', 'barcodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_tripsheets', sa.Column('barcodes', mysql.JSON(), nullable=False))
    # ### end Alembic commands ###
