"""Add warehouse_id to PickupAddress and Consignee

Revision ID: b2c53a77c0b1
Revises: fa3713df33ee
Create Date: 2026-08-04 14:17:30.447781

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b2c53a77c0b1'
down_revision: Union[str, None] = 'fa3713df33ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignees', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_consignees_warehouse_id'), 'consignees', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'consignees', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.add_column('pickup_addresses', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_pickup_addresses_warehouse_id'), 'pickup_addresses', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'pickup_addresses', 'warehouse_addresses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pickup_addresses', type_='foreignkey')
    op.drop_index(op.f('ix_pickup_addresses_warehouse_id'), table_name='pickup_addresses')
    op.drop_column('pickup_addresses', 'warehouse_id')
    op.drop_constraint(None, 'consignees', type_='foreignkey')
    op.drop_index(op.f('ix_consignees_warehouse_id'), table_name='consignees')
    op.drop_column('consignees', 'warehouse_id')
    # ### end Alembic commands ###
