"""Add latitude and longitude to entities

Revision ID: c5fabedcc295
Revises: 46173de05605
Create Date: 2026-07-16 15:31:11.859842

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'c5fabedcc295'
down_revision: Union[str, None] = '46173de05605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignees', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('consignees', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('franchises', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('franchises', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('pickup_addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pickup_addresses', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('warehouse_addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('warehouse_addresses', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_addresses', 'longitude')
    op.drop_column('warehouse_addresses', 'latitude')
    op.drop_column('pickup_addresses', 'longitude')
    op.drop_column('pickup_addresses', 'latitude')
    op.drop_column('franchises', 'longitude')
    op.drop_column('franchises', 'latitude')
    op.drop_column('consignees', 'longitude')
    op.drop_column('consignees', 'latitude')
    # ### end Alembic commands ###
