"""Add city, state, country to franchises

Revision ID: cd04b5acc164
Revises: 777d33343dcb
Create Date: 2026-07-27 10:05:20.880001

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cd04b5acc164'
down_revision: Union[str, None] = '777d33343dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('franchises', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('franchises', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('franchises', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('franchises', 'country')
    op.drop_column('franchises', 'state')
    op.drop_column('franchises', 'city')
    # ### end Alembic commands ###
