"""Add RazorpayTransaction model

Revision ID: cd913e94121b
Revises: 31e6b3d20eff
Create Date: 2026-07-30 23:01:11.918164

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cd913e94121b'
down_revision: Union[str, None] = '31e6b3d20eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_transactions_order_id'), 'razorpay_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_razorpay_transactions_razorpay_order_id'), 'razorpay_transactions', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_razorpay_transactions_razorpay_payment_id'), 'razorpay_transactions', ['razorpay_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_razorpay_transactions_razorpay_payment_id'), table_name='razorpay_transactions')
    op.drop_index(op.f('ix_razorpay_transactions_razorpay_order_id'), table_name='razorpay_transactions')
    op.drop_index(op.f('ix_razorpay_transactions_order_id'), table_name='razorpay_transactions')
    op.drop_table('razorpay_transactions')
    # ### end Alembic commands ###
