"""add_order_intransit_table

Revision ID: f6a6b3065741
Revises: f9b6aa0532c5
Create Date: 2026-07-27 12:56:33.259052

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f6a6b3065741'
down_revision: Union[str, None] = 'f9b6aa0532c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
