"""Add city, state, country to franchise_applications_byuser

Revision ID: f9b6aa0532c5
Revises: cd04b5acc164
Create Date: 2026-07-27 10:21:15.669855

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f9b6aa0532c5'
down_revision: Union[str, None] = 'cd04b5acc164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('franchise_applications_byuser', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('franchise_applications_byuser', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('franchise_applications_byuser', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('franchise_applications_byuser', 'country')
    op.drop_column('franchise_applications_byuser', 'state')
    op.drop_column('franchise_applications_byuser', 'city')
    # ### end Alembic commands ###
